---
- name: Windows playbook
  hosts: win
  gather_facts: false
  vars:
    acs_ip: "192.168.9.26"
  tasks:
    - name: Ping
      ansible.windows.win_ping:
    - name: Copy file
      ansible.windows.win_copy:
        src: helloworld.txt
        dest: C:\Users\vagrant\

    # Normally we could use win_chocolatey to install software. However when there
    # is a restricive firewall, or no internet access at all, we need to be able to
    # download the installer from within the network.
    # In this demo we fake it by running a webserver on the acs (192.168.9.26).
    # However this requires that you first download the installer to files/packages.
    # It is then accessible by the webserver through a VirtualBox synced folder, see the
    # Vagrantfile.
    - name: Install Notepad++
      ansible.windows.win_package:
        path: http://{{ acs_ip }}/npp.8.7.1.Installer.x64.exe
        # The product_id is used to check if the application has been installed.
        # For exe installers we need to use the name of the key under
        # HKLM\SOFTWARE\Microsoft\Windows\Current\Version\Uninstall, in this case Notepad++.
        # For MSIs etc you need something else, see the documentation of win_package.
        product_id: Notepad++
        # Figuring out which arguments to use for a silent installation can be a challenge.
        # I found this by googling:
        arguments: /S
      tags: notepadplusplus
