---
- name: Windows playbook
  hosts: win
  tasks:
    - name: Ping
      ansible.windows.win_ping:
    - name: Copy file
      ansible.windows.win_copy:
        src: helloworld.txt
        dest: C:\Users\vagrant\

